import fontTools.ttLib
import fontTools.ttLib.sfnt
import fontTools.subset
import fontTools.misc.loggingTools
import logging
import io
import multiprocessing.pool

fonts = ["C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/CSS/THEME/FONTS/FONTAWESOME-WEBFONT.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/CSS/THEME/FONTS/ICON-BRAND.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/CSS/THEME/FONTS/ROBOTO-REGULAR.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/GLYPHICONS-HALFLINGS-REGULAR.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ICON-LARGE.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ICON-SMALL.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ICON-UI.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/MUSEOSANSFORDELL-BOLD.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/MUSEOSANSFORDELL-REGULAR.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ROBOTO-BLACK.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ROBOTO-BOLD.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ROBOTO-LIGHT.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ROBOTO-MEDIUM.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ROBOTO-REGULAR.TTF",
    "C:/PROGRAM FILES/DELL/SUPPORTASSISTAGENT/BIN/APP/CONTENT/FONTS/ROBOTO-THIN.TTF",
    "C:/WINDOWS/FONTS/ALDHABI.TTF",
    "C:/WINDOWS/FONTS/ALIENWARE_CARET_FONT.TTF",
    "C:/WINDOWS/FONTS/ANDLSO.TTF",
    "C:/WINDOWS/FONTS/ARABTYPE.TTF",
    "C:/WINDOWS/FONTS/ARIAL.TTF",
    "C:/WINDOWS/FONTS/ARIALBD.TTF",
    "C:/WINDOWS/FONTS/ARIALBI.TTF",
    "C:/WINDOWS/FONTS/ARIALI.TTF",
    "C:/WINDOWS/FONTS/ARIBLK.TTF",
    "C:/WINDOWS/FONTS/BAHNSCHRIFT.TTF",
    "C:/WINDOWS/FONTS/CALIBRI.TTF",
    "C:/WINDOWS/FONTS/CALIBRIB.TTF",
    "C:/WINDOWS/FONTS/CALIBRII.TTF",
    "C:/WINDOWS/FONTS/CALIBRIL.TTF",
    "C:/WINDOWS/FONTS/CALIBRILI.TTF",
    "C:/WINDOWS/FONTS/CALIBRIZ.TTF",
    "C:/WINDOWS/FONTS/CAMBRIA.TTC",
    "C:/WINDOWS/FONTS/CAMBRIAB.TTF",
    "C:/WINDOWS/FONTS/CAMBRIAI.TTF",
    "C:/WINDOWS/FONTS/CAMBRIAZ.TTF",
    "C:/WINDOWS/FONTS/CANDARA.TTF",
    "C:/WINDOWS/FONTS/CANDARAB.TTF",
    "C:/WINDOWS/FONTS/CANDARAI.TTF",
    "C:/WINDOWS/FONTS/CANDARAL.TTF",
    "C:/WINDOWS/FONTS/CANDARALI.TTF",
    "C:/WINDOWS/FONTS/CANDARAZ.TTF",
    "C:/WINDOWS/FONTS/COMIC.TTF",
    "C:/WINDOWS/FONTS/COMICBD.TTF",
    "C:/WINDOWS/FONTS/COMICI.TTF",
    "C:/WINDOWS/FONTS/COMICZ.TTF",
    "C:/WINDOWS/FONTS/CONSOLA.TTF",
    "C:/WINDOWS/FONTS/CONSOLAB.TTF",
    "C:/WINDOWS/FONTS/CONSOLAI.TTF",
    "C:/WINDOWS/FONTS/CONSOLAZ.TTF",
    "C:/WINDOWS/FONTS/CONSTAN.TTF",
    "C:/WINDOWS/FONTS/CONSTANB.TTF",
    "C:/WINDOWS/FONTS/CONSTANI.TTF",
    "C:/WINDOWS/FONTS/CONSTANZ.TTF",
    "C:/WINDOWS/FONTS/CORBEL.TTF",
    "C:/WINDOWS/FONTS/CORBELB.TTF",
    "C:/WINDOWS/FONTS/CORBELI.TTF",
    "C:/WINDOWS/FONTS/CORBELL.TTF",
    "C:/WINDOWS/FONTS/CORBELLI.TTF",
    "C:/WINDOWS/FONTS/CORBELZ.TTF",
    "C:/WINDOWS/FONTS/COUR.TTF",
    "C:/WINDOWS/FONTS/COURBD.TTF",
    "C:/WINDOWS/FONTS/COURBI.TTF",
    "C:/WINDOWS/FONTS/COURI.TTF",
    "C:/WINDOWS/FONTS/DENG.TTF",
    "C:/WINDOWS/FONTS/DENGB.TTF",
    "C:/WINDOWS/FONTS/DENGL.TTF",
    "C:/WINDOWS/FONTS/EBRIMA.TTF",
    "C:/WINDOWS/FONTS/EBRIMABD.TTF",
    "C:/WINDOWS/FONTS/FRAMD.TTF",
    "C:/WINDOWS/FONTS/FRAMDIT.TTF",
    "C:/WINDOWS/FONTS/GABRIOLA.TTF",
    "C:/WINDOWS/FONTS/GADUGI.TTF",
    "C:/WINDOWS/FONTS/GADUGIB.TTF",
    "C:/WINDOWS/FONTS/GEORGIA.TTF",
    "C:/WINDOWS/FONTS/GEORGIAB.TTF",
    "C:/WINDOWS/FONTS/GEORGIAI.TTF",
    "C:/WINDOWS/FONTS/GEORGIAZ.TTF",
    "C:/WINDOWS/FONTS/HIMALAYA.TTF",
    "C:/WINDOWS/FONTS/HOLOMDL2.TTF",
    "C:/WINDOWS/FONTS/IMPACT.TTF",
    "C:/WINDOWS/FONTS/INKFREE.TTF",
    "C:/WINDOWS/FONTS/JAVATEXT.TTF",
    "C:/WINDOWS/FONTS/LEELAUIB.TTF",
    "C:/WINDOWS/FONTS/LEELAWUI.TTF",
    "C:/WINDOWS/FONTS/LEELUISL.TTF",
    "C:/WINDOWS/FONTS/LUCON.TTF",
    "C:/WINDOWS/FONTS/L_10646.TTF",
    "C:/WINDOWS/FONTS/MAJALLA.TTF",
    "C:/WINDOWS/FONTS/MAJALLAB.TTF",
    "C:/WINDOWS/FONTS/MALGUN.TTF",
    "C:/WINDOWS/FONTS/MALGUNBD.TTF",
    "C:/WINDOWS/FONTS/MALGUNSL.TTF",
    "C:/WINDOWS/FONTS/MARLETT.TTF",
    "C:/WINDOWS/FONTS/MICROSS.TTF",
    "C:/WINDOWS/FONTS/MINGLIUB.TTC",
    "C:/WINDOWS/FONTS/MMRTEXT.TTF",
    "C:/WINDOWS/FONTS/MMRTEXTB.TTF",
    "C:/WINDOWS/FONTS/MONBAITI.TTF",
    "C:/WINDOWS/FONTS/MSGOTHIC.TTC",
    "C:/WINDOWS/FONTS/MSJH.TTC",
    "C:/WINDOWS/FONTS/MSJHBD.TTC",
    "C:/WINDOWS/FONTS/MSJHL.TTC",
    "C:/WINDOWS/FONTS/MSUIGHUB.TTF",
    "C:/WINDOWS/FONTS/MSUIGHUR.TTF",
    "C:/WINDOWS/FONTS/MSYH.TTC",
    "C:/WINDOWS/FONTS/MSYHBD.TTC",
    "C:/WINDOWS/FONTS/MSYHL.TTC",
    "C:/WINDOWS/FONTS/MSYI.TTF",
    "C:/WINDOWS/FONTS/MVBOLI.TTF",
    "C:/WINDOWS/FONTS/NIRMALA.TTF",
    "C:/WINDOWS/FONTS/NIRMALAB.TTF",
    "C:/WINDOWS/FONTS/NIRMALAS.TTF",
    "C:/WINDOWS/FONTS/NTAILU.TTF",
    "C:/WINDOWS/FONTS/NTAILUB.TTF",
    "C:/WINDOWS/FONTS/PALA.TTF",
    "C:/WINDOWS/FONTS/PALAB.TTF",
    "C:/WINDOWS/FONTS/PALABI.TTF",
    "C:/WINDOWS/FONTS/PALAI.TTF",
    "C:/WINDOWS/FONTS/PHAGSPA.TTF",
    "C:/WINDOWS/FONTS/PHAGSPAB.TTF",
    "C:/WINDOWS/FONTS/SEGMDL2.TTF",
    "C:/WINDOWS/FONTS/SEGOEPR.TTF",
    "C:/WINDOWS/FONTS/SEGOEPRB.TTF",
    "C:/WINDOWS/FONTS/SEGOESC.TTF",
    "C:/WINDOWS/FONTS/SEGOESCB.TTF",
    "C:/WINDOWS/FONTS/SEGOEUI.TTF",
    "C:/WINDOWS/FONTS/SEGOEUIB.TTF",
    "C:/WINDOWS/FONTS/SEGOEUII.TTF",
    "C:/WINDOWS/FONTS/SEGOEUIL.TTF",
    "C:/WINDOWS/FONTS/SEGOEUISL.TTF",
    "C:/WINDOWS/FONTS/SEGOEUIZ.TTF",
    "C:/WINDOWS/FONTS/SEGUIBL.TTF",
    "C:/WINDOWS/FONTS/SEGUIBLI.TTF",
    "C:/WINDOWS/FONTS/SEGUIEMJ.TTF",
    "C:/WINDOWS/FONTS/SEGUIHIS.TTF",
    "C:/WINDOWS/FONTS/SEGUILI.TTF",
    "C:/WINDOWS/FONTS/SEGUISB.TTF",
    "C:/WINDOWS/FONTS/SEGUISBI.TTF",
    "C:/WINDOWS/FONTS/SEGUISLI.TTF",
    "C:/WINDOWS/FONTS/SEGUISYM.TTF",
    "C:/WINDOWS/FONTS/SIMFANG.TTF",
    "C:/WINDOWS/FONTS/SIMHEI.TTF",
    "C:/WINDOWS/FONTS/SIMKAI.TTF",
    "C:/WINDOWS/FONTS/SIMPBDO.TTF",
    "C:/WINDOWS/FONTS/SIMPFXO.TTF",
    "C:/WINDOWS/FONTS/SIMPO.TTF",
    "C:/WINDOWS/FONTS/SIMSUN.TTC",
    "C:/WINDOWS/FONTS/SIMSUNB.TTF",
    "C:/WINDOWS/FONTS/SITKA.TTC",
    "C:/WINDOWS/FONTS/SITKAB.TTC",
    "C:/WINDOWS/FONTS/SITKAI.TTC",
    "C:/WINDOWS/FONTS/SITKAZ.TTC",
    "C:/WINDOWS/FONTS/SYLFAEN.TTF",
    "C:/WINDOWS/FONTS/SYMBOL.TTF",
    "C:/WINDOWS/FONTS/TAHOMA.TTF",
    "C:/WINDOWS/FONTS/TAHOMABD.TTF",
    "C:/WINDOWS/FONTS/TAILE.TTF",
    "C:/WINDOWS/FONTS/TAILEB.TTF",
    "C:/WINDOWS/FONTS/TIMES.TTF",
    "C:/WINDOWS/FONTS/TIMESBD.TTF",
    "C:/WINDOWS/FONTS/TIMESBI.TTF",
    "C:/WINDOWS/FONTS/TIMESI.TTF",
    "C:/WINDOWS/FONTS/TRADBDO.TTF",
    "C:/WINDOWS/FONTS/TRADO.TTF",
    "C:/WINDOWS/FONTS/TREBUC.TTF",
    "C:/WINDOWS/FONTS/TREBUCBD.TTF",
    "C:/WINDOWS/FONTS/TREBUCBI.TTF",
    "C:/WINDOWS/FONTS/TREBUCIT.TTF",
    "C:/WINDOWS/FONTS/URDTYPE.TTF",
    "C:/WINDOWS/FONTS/URDTYPEB.TTF",
    "C:/WINDOWS/FONTS/VERDANA.TTF",
    "C:/WINDOWS/FONTS/VERDANAB.TTF",
    "C:/WINDOWS/FONTS/VERDANAI.TTF",
    "C:/WINDOWS/FONTS/VERDANAZ.TTF",
    "C:/WINDOWS/FONTS/WEBDINGS.TTF",
    "C:/WINDOWS/FONTS/WINGDING.TTF",
    "C:/WINDOWS/FONTS/YUGOTHB.TTC",
    "C:/WINDOWS/FONTS/YUGOTHL.TTC",
    "C:/WINDOWS/FONTS/YUGOTHM.TTC",
    "C:/WINDOWS/FONTS/YUGOTHR.TTC"]

def size(path, fontNumber, glyphs):
    options = fontTools.subset.Options()
    subsetter = fontTools.subset.Subsetter(options=options)
    subsetter.populate(glyphs=glyphs, gids=[], unicodes=[], text="")
    font = fontTools.ttLib.TTFont(path, fontNumber=fontNumber)
    subsetter.subset(font)
    stream = io.BytesIO()
    font.save(stream)
    stream.seek(0, 2)
    byteCount = stream.tell()
    stream.seek(0, 0)
    font = fontTools.ttLib.TTFont(stream)
    return len(font.getGlyphOrder())

def sizeHelper(t):
    return size(t[0], t[1], t[2])

def getNumFonts(file):
    sfntVersion = file.read(4)
    file.seek(0)
    if sfntVersion == b"ttcf":
        header = fontTools.ttLib.sfnt.readTTCHeader(file)
        return header.numFonts
    return 1

if __name__ == '__main__':
    fontTools.misc.loggingTools.configLogger(level=logging.FATAL)
    for i in range(len(fonts)):
        path = fonts[i]
        print("Investigating font " + str(i) + " " + path)
        file = open(path, "rb")
        for fontNumber in range(getNumFonts(file)):
            font = fontTools.ttLib.TTFont(file, fontNumber=fontNumber)
            glyphOrder = font.getGlyphOrder()
            workQueue = []
            for glyphIndex in range(1, len(glyphOrder)):
                workQueue.append((path, fontNumber, glyphOrder[:glyphIndex]))
            with multiprocessing.pool.Pool() as pool:
                print(pool.map(sizeHelper, workQueue))
        file.close()
